### ISSUE TITLE
Error when using docker image

### ISSUE THREAD

**Issue by devyan13** [rauversion/rauversion-phx#130]
Hello,
I have successfully created a docker image using the dockerfile, but I always get the following error message on startup:
```
rauversion    | "prod" 
rauversion    | ERROR! Config provider Config.Reader failed with: 
rauversion    | ** (FunctionClauseError) no function clause matching in Base.decode64/2
rauversion    |     (elixir 1.13.4) lib/base.ex:404: Base.decode64(nil, [])
rauversion    |     (stdlib 4.0.1) erl_eval.erl:744: :erl_eval.do_apply/7
rauversion    |     (stdlib 4.0.1) erl_eval.erl:323: :erl_eval.expr/6
rauversion    |     (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3
rauversion    |     (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3
rauversion    |     (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
rauversion    |     (elixir 1.13.4) lib/config.ex:260: Config.__eval__!/3
rauversion    |     (elixir 1.13.4) lib/config/reader.ex:92: Config.Reader.read!/2
rauversion    |
rauversion    | {"init terminating in do_boot",{function_clause,[{'Elixir.Base',decode64,[nil,[]],[{file,"lib/base.ex"},{line,404}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,744}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,323}]},{elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,296}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,274}]},{'Elixir.Code',validated_eval_string,3,[{file,"lib/code.ex"},{line,404}]},{'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,260}]},{'Elixir.Config.Reader','read!',2,[{file,"lib/config/reader.ex"},{line,92}]}]}}
rauversion    | init terminating in do_boot ({function_clause,[{Elixir.Base,decode64,[nil,[_]],[{_},{_}]},{erl_eval,do_apply,7,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{elixir,recur_eval,3,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},=ERROR REPORT==== 16-Dec-2022::16:57:42.468321 ===
rauversion    | Error in process <0.9.0> on node rauversion@5b27af1f2c47 with exit value:
rauversion    | {function_clause,
rauversion    |     [{'Elixir.Base',decode64,[nil,[]],[{file,"lib/base.ex"},{line,404}]},
rauversion    |      {erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,744}]},
rauversion    |      {erl_eval,expr,6,[{file,"erl_eval.erl"},{line,323}]},
rauversion    |      {elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,296}]},
rauversion    |      {elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,274}]},
rauversion    |      {'Elixir.Code',validated_eval_string,3,[{file,"lib/code.ex"},{line,404}]},
rauversion    |      {'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,260}]},
rauversion    |      {'Elixir.Config.Reader','read!',2,
rauversion    |          [{file,"lib/config/reader.ex"},{line,92}]}]}
rauversion    |
rauversion    | {Elixir.Config,__eval__!,3,[{_},{_}]},{Elixir.Config.Reader,read!,2,[{_},{_}]}]})
rauversion    |  
rauversion    | Crash dump is being written to: erl_crash.dump...done 
```
Does anyone know what to do here to get rauversion running with docker?

**Comment by michelson** [comment]
Hi! are you providing the env variables?
are you running this locally or for production?
there is already an image on [dockerhub](https://hub.docker.com/r/michelson/rauversion)

**Comment by devyan13** [comment]
I am trying to run it in production and am providing the env variables.
I start the whole thing with docker compose and have tested different configurations. Here is an example:
```
version: '3.7' 
services:

  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - "web"

  rauversion:
    image: michelson/rauversion:latest
    container_name: rauversion
    env_file:
      - .env
    environment:
      - PORT:4000
      - DB_HOST:db
      - MIX_BUILD_ROOT:/opt/elixir-artifacts/_build # Moves build and deps out of the workspace for performance
      - MIX_DEPS_PATH:/opt/elixir-artifacts/deps
    expose:
      - 4000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rauversion.rule=Host(`removed`)"
      - "traefik.http.routers.rauversion.entrypoints=websecure"
      - "traefik.http.routers.rauversion.tls.certresolver=myresolver"
    networks:
     - "web"
networks:
  web:
    external: true
```

Then I get this error message:

```
Starting rauversion-phx_db_1 ... done
Starting rauversion          ... done
Attaching to rauversion-phx_db_1, rauversion 
db_1          |
db_1          | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1          |
db_1          | 2022-12-16 18:20:11.299 UTC [1] LOG:  starting PostgreSQL 14.3 (Debian 14.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db_1          | 2022-12-16 18:20:11.299 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1          | 2022-12-16 18:20:11.299 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1          | 2022-12-16 18:20:11.312 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432" 
db_1          | 2022-12-16 18:20:11.329 UTC [26] LOG:  database system was shut down at 2022-12-16 18:18:32 UTC 
db_1          | 2022-12-16 18:20:11.339 UTC [1] LOG:  database system is ready to accept connections 
rauversion    | ERROR! Config provider Config.Reader failed with: 
rauversion    | ** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
rauversion    |     Mix.env() 
rauversion    |     (stdlib 4.0.1) erl_eval.erl:744: :erl_eval.do_apply/7
rauversion    |     (stdlib 4.0.1) erl_eval.erl:537: :erl_eval.expr/6
rauversion    |     (stdlib 4.0.1) erl_eval.erl:323: :erl_eval.expr/6
rauversion    |     (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3
rauversion    |     (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3
rauversion    |     (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
rauversion    |     (elixir 1.13.4) lib/config.ex:260: Config.__eval__!/3
rauversion    |
rauversion    | {"init terminating in do_boot",{undef,[{'Elixir.Mix',env,[],[]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,744}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,537}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,323}]},{elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,296}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,274}]},{'Elixir.Code',validated_eval_string,3,[{file,"lib/code.ex"},{line,404}]},{'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,260}]}]}}
rauversion    | init terminating in do_boot ({undef,[{Elixir.Mix,env,[],[]},{erl_eval,do_apply,7,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{elixir,recur_eval,3,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,3,[{_},{_}]}]})
rauversion    |
rauversion    | Crash dump is being written to: erl_crash.dump...done 
rauversion exited with code 1 
```
